version: '3'
services:
    laravel.test:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '8080:8080'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            PHP_IDE_CONFIG: '${PHP_IDE_CONFIG:-serverName=localhost}'
        volumes:
            - '.:/var/www/html'
            - './docker/php/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini'
            - './docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf'
        networks:
            - sail

networks:
    sail:
        driver: bridge

